### ISSUE TITLE
How to send emails

### ISSUE THREAD

**Issue by mayurpande** [mneedham91/PyPardot4#31]
How do I send an email? Does the email account need to be added before hand? I have been looking at this documentation. But cannot figure it out.

**Comment by mneedham91** [comment]
Check out the _send_to_email_, _send_to_id_, and _send_to_lists_ methods [here](https://github.com/mneedham91/PyPardot4/wiki/Emails)

**Comment by mayurpande** [comment]
Brilliant thanks I got it to work, but had to use lots of different parameters from this list http://developer.pardot.com/kb/api-version-4/emails/#sending-one-to-one-emails. I have another question, I have a html email how do I get the images within the email to show/be sent too. I have tried to use full urls but this did not work
