### ISSUE TITLE
bulk does not work for some API endpoints

### ISSUE THREAD

**Issue by chb777777** [mneedham91/PyPardot4#36]
dynamicContent,
campaign,
prospectAccount
lifecyclehistories

so far I found output='bulk' does not work for these endpoints. I installed the package using pypi, is github version here ahead of Pypi package?

**Comment by chb777777** [comment]
Looking at some of the code, it seems that bulk is not included with many of these API endpoints, is that correct?

**Comment by mneedham91** [comment]
Hi @chb777777 according to the official API documentation, output=bulk is not available for those endpoints. For example, see [here](http://developer.pardot.com/kb/api-version-4/lifecycle-histories/) for Lifecycle Histories.

PS PyPi and GitHub should be in sync.

**Comment by chb777777** [comment]
@mneedham91 Not sure if the page you linked is where you see if bulk output is available  since the other pages which bulk is enabled also does not show under the API page. However, on a separate page, it does show that output=bulk is generally available. 
Also, after testing using Postman, it also seems like that bulk is available for all endpoints.
